### ISSUE TITLE
SenseCAP Watcher: 3D model available?

### ISSUE THREAD

**Issue by gmacario** [Seeed-Studio/OSHW-SenseCAP-Watcher#1]
First of all, congratulations for making this repository public and releasing the SenseCAP Watcher hardware design under an Open Source license!

Following up to [a question I asked on Seeed Studio Forum a few weeks ago](https://forum.seeedstudio.com/t/sensecap-watcher-3d-model-available/280964), do you also plan to release the 3D models of the Watcher enclosure?

As I explained in my post, as part of our [FREISA Robot-Dog project](https://github.com/B-AROL-O/FREISA), we plan to design some additional 3D-printable adapters and fixtures for the SenseCAP Watcher - please refer to [our post on Hackster](https://www.hackster.io/b-arol-o/freisa-meets-sensecap-watcher-89596b) for details.

It would be quite helpful if Seeed Studio could share the 3D model of the Watcher enclosure. Any common mechanical CAD 3D model (i.e. SolidWorks, IGES, STEP) could help a lot.

On the other hand, if you do not plan to release the 3D model just let us know.

**Comment by limengdu** [comment]
Hello, SenseCAP Watcher is currently patent pending and we are unable to provide the full STEP file immediately. What kind of requirements do you have, maybe I can apply for a partial (e.g. appearance) STEP for you, and when we have everything ready, we will publish it in full.

**Comment by limengdu** [comment]
https://github.com/Seeed-Studio/OSHW-SenseCAP-Watcher/blob/main/Hardware/SenseCAP_Watcher-3D-Shell_v1.stp
